name: Deploy Components to Mainnet
on:
  push:
    branches: [main, ci-test]
jobs:
  deploy-mainnet:
    name: Deploy widgets to social.near (mainnet)
    runs-on: ubuntu-latest
    environment: infrastructure-committee.near
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install near-social CLI
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/FroVolod/bos-cli-rs/releases/download/v0.3.14/bos-cli-v0.3.14-installer.sh | sh
      - name: Deploy widgets
        run: |
          bos components deploy '${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}' sign-as '${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}' network-config mainnet sign-with-plaintext-private-key --signer-public-key '${{ vars.NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY }}' --signer-private-key '${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}' send
