name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: bos-cli-rs/bos-cli-rs/.github/workflows/deploy-mainnet.yml@master
    with:
      deploy-account-address: ${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}
      signer-account-address: ${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}
      signer-public-key: ${{ vars.NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY }}
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}
