name: Deploy Components to Mainnet
on:
  push:
    branches: [main, ci-test]
jobs:
  # NOTE: GitHub Actions does not support `environment` directly on the jobs that use `uses`, so we need this additional step
  vars:
    runs-on: ubuntu-latest
    environment: infrastructure-committee.near
    outputs:
      target-account-id: ${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}
      signer-public-key: ${{ vars.NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY }}
      signer-private-key: ${{ vars.NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY }}
    steps:
      - id: vars
        run: echo 'NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY=${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}' >> "$GITHUB_OUTPUT"

  inspect:
    needs: [vars]
    runs-on: ubuntu-latest
    environment: infrastructure-committee.near
    steps:
    - run: |
        echo 'deploy-account-address ${{ needs.vars.outputs.target-account-id }} signer-account-address ${{ needs.vars.outputs.target-account-id }} signer-public-key ${{ needs.vars.outputs.signer-public-key }} SIGNER_PRIVATE_KEY ${{ needs.vars.outputs.signer-private-key }}'
        echo 'SEC: ${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}'

  deploy-mainnet:
    needs: [vars]
    uses: bos-cli-rs/bos-cli-rs/.github/workflows/deploy-mainnet.yml@main
    with:
      deploy-account-address: ${{ needs.vars.outputs.target-account-id }}
      signer-account-address: ${{ needs.vars.outputs.target-account-id }}
      signer-public-key: ${{ needs.vars.outputs.signer-public-key }}
    secrets:
      SIGNER_PRIVATE_KEY: ${{ needs.vars.outputs.signer-private-key }}
